# Generated by Django 2.0.4 on 2018-04-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20180426_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='section',
            new_name='section_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='subsection',
            new_name='subsection_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='test',
            new_name='test_id',
        ),
        migrations.AlterField(
            model_name='clienttype',
            name='client_type',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='type_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='subsection_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subsubsection',
            name='subsubsection_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
