# Generated by Django 2.0.4 on 2018-04-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20180426_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversionChart',
            new_name='ScoreConversion',
        ),
        migrations.AlterModelTable(
            name='scoreconversion',
            table='score_conversions',
        ),
    ]
