# Generated by Django 2.0.4 on 2018-04-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20180426_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreConversionMath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_correct', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Test')),
            ],
            options={
                'db_table': 'math_score_conversions',
            },
        ),
        migrations.CreateModel(
            name='ScoreConversionReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_correct', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Test')),
            ],
            options={
                'db_table': 'reading_score_conversions',
            },
        ),
        migrations.CreateModel(
            name='ScoreConversionWriting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_correct', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Test')),
            ],
            options={
                'db_table': 'writing_score_conversions',
            },
        ),
        migrations.RemoveField(
            model_name='scoreconversion',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='scoreconversion',
            name='test_id',
        ),
        migrations.DeleteModel(
            name='ScoreConversion',
        ),
    ]
