# Generated by Django 2.0.4 on 2018-04-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20180426_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScoreConversionWriting',
            new_name='MathScoreConversion',
        ),
        migrations.RenameModel(
            old_name='ScoreConversionMath',
            new_name='ReadingScoreConversion',
        ),
        migrations.RenameModel(
            old_name='ScoreConversionReading',
            new_name='WritingScoreConversion',
        ),
        migrations.AlterModelTable(
            name='mathscoreconversion',
            table='math_score_conversions',
        ),
        migrations.AlterModelTable(
            name='readingscoreconversion',
            table='reading_score_conversions',
        ),
        migrations.AlterModelTable(
            name='writingscoreconversion',
            table='writing_score_conversions',
        ),
    ]
